### ISSUE TITLE
Getting Error for Level 0

### ISSUE THREAD

**Issue by hengyjj** [nus-cs2030/2122-s2#102]
# Summary
Put a summary of the question

## Description 
Hi! As I was running the codes for Level 0, I keep getting this error.

![image](https://user-images.githubusercontent.com/77519191/158748881-880cf567-5883-45d2-b437-8f431e82e357.png)

This is the question that I am talking about.
![image](https://user-images.githubusercontent.com/77519191/158748933-e816fa3b-0ec8-4a76-b617-51a2f214178c.png)

I know the error has got to do with PQ and Comparator as they are both of different types (String and Object) but I am unsure on what to rectify. I tried to let T extends Object but it doesn't work.

Thank you!
 

## Screenshots (if any): 
Insert Images here if necessary

**Comment by LauWyeRock** [comment]
I don't think it should be T extends object but rather ? super T

**Comment by szeying02** [comment]
Hi! You might want to consider modifying the generic for the constructor PQ that takes in the comparator, to take in the super classes of type T instead of the sub class of type T. In other words, `Comparator<? super T>`. Hope this helps!

**Comment by hengyjj** [comment]
> I don't think it should be T extends object but rather ? super T

thank you!

**Comment by hengyjj** [comment]
> Hi! You might want to consider modifying the generic for the constructor PQ that takes in the comparator, to take in the super classes of type T instead of the sub class of type T. In other words, `Comparator<? super T>`. Hope this helps!

hi szeying! thank you for your help. i tried but another error pops up. 
![image](https://user-images.githubusercontent.com/77519191/158752697-2cb502ec-3144-4528-bf7a-efa4705fe4e0.png)

**Comment by szeying02** [comment]
Hi, I think you may have forgotten to do this part (front part of the test cases for the level):
`PQ<String> pq = new PQ<String>(cmp)`

**Comment by hengyjj** [comment]
> I think you may have forgotten to do this part (front part of the test cases for the level): `PQ<String> pq = new PQ<String>(cmp)`

thank you so much szeying!!

**Comment by Darien2307** [comment]
Hi, apologies. It seems Level 0 involves some of the concepts we have learnt from week 7 and 8 but I'm having some difficulty.
I am assuming PQ will take have an ImList to perform the add and poll methods right?
But because we are not supposed to edit the ImList method and the constructors are private, how do we go about creating the imList in PQ? Or is it my approach is wrong?
Could someone enlighten me? 
Thank you!

**Comment by LauWyeRock** [comment]
>PQ doesnt take an ImList, you can directly use the PriorityQueue class of java.util.PriorityQueue. I think this clears up all the errors you may have

**Comment by hengyjj** [comment]
> Hi, apologies. It seems Level 0 involves some of the concepts we have learnt from week 7 and 8 but I'm having some difficulty. I am assuming PQ will take have an ImList to perform the add and poll methods right? But because we are not supposed to edit the ImList method and the constructors are private, how do we go about creating the imList in PQ? Or is it my approach is wrong? Could someone enlighten me? Thank you!

Hi Darien! For me, I created an ImList within the PQ class for the add and poll method. Referring to Lecture 8, creating ImList can be done by typing `ImList.<T>of()` instead of the usual `new ImList()` that we are used to. Hope this clarifies!

**Comment by szeying02** [comment]
Actually, the add() and poll() method are also part of java.util.PriorityQueue, so it's not quite necessarily to have an ImList within the PQ class.

**Comment by hengyjj** [comment]
> Actually, the add() and poll() method are also part of java.util.PriorityQueue, so it's not quite necessarily to have an ImList within the PQ class.

i see.. thanks for mentioning it!

**Comment by Darien2307** [comment]
Thanks @szeying02 Sze Ying for the advice too! Actually I also saw in this in an earlier paragraph in the qn but I find that ImList is pretty useful/resonate more with me regarding Level 0 itself...
@hengyjj Yi Jie, thank you for bringing up the possibility of ImList. But can I clarify, the `ImList.<T>of()` is an imList method rather than the constructors right? How did you initiate the imlist though?
My idea is pq has the properties of a comparator and an imlist. For Imlist, I was trying
`ImList<T> list = new ImList.<T>of();
this.list = list;` 
but 
<img width="416" alt="image" src="https://user-images.githubusercontent.com/77558445/158779779-4b54c4eb-db4c-437a-af7f-8690ccde56ad.png">
which I also suppose so for the error to occur because im supposed to create based on a constructor not the method right?
Thanks in advance.

**Comment by szeying02** [comment]
I think what you're going for is:

`ImList<T> list = ImList.<T>of()`

**Comment by hengyjj** [comment]
> Thanks @szeying02 Sze Ying for the advice too! Actually I also saw in this in an earlier paragraph in the qn but I find that ImList is pretty useful/resonate more with me regarding Level 0 itself... @hengyjj Yi Jie, thank you for bringing up the possibility of ImList. But can I clarify, the `ImList.<T>of()` is an imList method rather than the constructors right? How did you initiate the imlist though? My idea is pq has the properties of a comparator and an imlist. For Imlist, I was trying `ImList<T> list = new ImList.<T>of(); this.list = list;` but <img alt="image" width="416" src="https://user-images.githubusercontent.com/77558445/158779779-4b54c4eb-db4c-437a-af7f-8690ccde56ad.png"> which I also suppose so for the error to occur because im supposed to create based on a constructor not the method right? Thanks in advance.

Hi Darien. I am not too sure but I believe it is a static method (You could refer to the ImList class) and hence we are able to call it directly from another class just by typing `ImList<T> list = ImList.<T>of();` and this method will create a new ImList. I might be wrong on this so someone please correct me if I am wrong.

**Comment by Darien2307** [comment]
Hi Sze Ying and Yi Jie, yup haha both of you are right! I should not have put "new". 
Thanks for all your help! All the best for the project, labs and finals!!
