### ISSUE TITLE
Overriding put method in level 2 

### ISSUE THREAD

**Issue by fionlim** [nus-cs2030/2122-s2#122]
Hello! For KeyableMap, if we override the put method in the Module and Student classes, then is it possible to implement the KeyableMap as an abstract class instead?

**Comment by yjjjiajie** [comment]
seems possible, but since codecrunch implemented KeyableMap as concrete class, I just followed haha

**Comment by szeying02** [comment]
Yup, should be possible if we don't need to define the put method directly / turn the method into an abstract method in KeyableMap (KeyableMap's put() instantiates KeyableMap I believe).

**Comment by Brianliew77** [comment]
Yep I believe that it is possible to implement it as an abstract class but for KeyableMap it is actually straightforward to implement as a concrete class. Just see it as a parent class that Module and Student inherits from

**Comment by summerthia02** [comment]
that was what i had thought initially since the methods will ultimately be overridden. And I do think it is completely fine to use an abstract method, all the more since the question stated that a class can be used. (because an abstract class is less specific than a class if I'm not wrong)
but in this case, since the question states that the keyablemap is a class, we could just use it as a class and implement the put method  - so that we can directly call keyable map's put method via super in the module  / student class 
for e.g. super.map().put(...)
