### ISSUE TITLE
PQ.add()

### ISSUE THREAD

**Issue by NWH21** [nus-cs2030/2122-s2#132]
I am currently attempting level 1 for the project. However, the add method resulted in some confusion as the output is [1.700, 3.500, 2.600] as compared to level 0 where the add method adds to the back of the list ([one, two, three]). Could someone enlighten me as to how to implement the add method properly in the PQ class?

**Comment by SpectralMusket** [comment]
add doesn't add to the back of the queue, it adds to the PriorityQueue and its placement is decided by the comparator you pass in.

So for example if we were inserting integers, and the comparator is simply comparing their values, then pq.add(3).add(2).add(5).add(1), instead of producing [1,5,2,3] like a normal queue would, it would produce something like [1,3,2,5] or something. 
Note that it does not maintain the order of the value of the elements (here 3 can come before 2 but 3>2), but it guarantees that the first element is definitely the smallest, and whenever the first element is taken out of the queue it "resorts" (technically not sorting) some of the elements such that the smallest one will end up on top. This took me quite a while to understand as well.

In the level 0 example the Comparator I believe is comparing their lexicographical value, which I think is the alphabetical order + case of the letters(? not sure about the exact formula).
It just so happens that "one" < "two" & "three" since 'o' comes before 't' in the alphabet. You can see it doesn't preserve relative ordering because in the next poll() example the "three" comes before "two", and if you go into jshell and do `"three".compareTo("two")` you really do see that "three" comes before "two".

**Comment by Keefetgy** [comment]
I believe you can refer to the ImList example on how to implement add.

**Comment by ReganKvioke** [comment]
Yeap the add method is very similar to that of ImList, you can refer to the PriorityQueue jdk API for more info

**Comment by rexlionz** [comment]
Hi, similar to what keefe has mentioned, you should try to implement add by looking at your ImList code! It helped me alot too
