### ISSUE TITLE
Level 7 Project test case 7_3

### ISSUE THREAD

**Issue by mingshan2705** [nus-cs2030/2122-s2#175]
Is anyone able to get test case 7_3 to work? Usually all the test cases are shown on Codecrunch but this one wasn't, and the test output kinda makes me think its a missing test case

<img width="404" alt="image" src="https://user-images.githubusercontent.com/85282762/160566228-53861c46-3391-4116-8f9a-714db90d07bb.png">

**Comment by mingshan2705** [comment]
Did you manage to pass 7_3? @LauWyeRock

**Comment by LauWyeRock** [comment]
HAHAHA i was just kidding but no i havent reached there yet

i havent seen "Time limit exceeded" before leh maybe you wanna clarify with your TA or smth

**Comment by daitenshionyan** [comment]
Hello!! I think your code is stuck in an infinite loop as the event queue is never emptied. This will cause the `run` method to never return a String and thus not output anything.

I had a similar problem when testing test case 7_2. The problem was in my server where it does not go back to being available (free to serve) after taking a break and its break time has ended. This caused all the remaining queued up customers on that server to never be served for the structure of my code and thus their respective Events remain in the queue forever. After fixing the availability problem it works.

**Comment by mingshan2705** [comment]
wow thanks @daitenshionyan! that was really helpful :D

**Comment by Lu-Yi-Fan** [comment]
@summerthia02
