### ISSUE TITLE
Restricted API detected: java.util.Objects

### ISSUE THREAD

**Issue by seanpbteo** [nus-cs2030/2122-s2#182]
# Summary
Hello all, I received this message in codecrunch when submitting files for my project in level 2. Has anyone else encountered the same problem? I did not import java.util.Objects in any class.

## Description 
I initially thought that using the static Double.compare was the issue but I still received the same problem after using the commented out code.

## Screenshots (if any): 
Insert Images here if necessary
<img width="1108" alt="image" src="https://user-images.githubusercontent.com/99883397/160959954-c8c6368b-8273-4e99-8c53-95a884d4c89e.png">

**Comment by LohYangXian** [comment]
Hi! I had this problem too! For me I realised that it was because I initialized my field outside of the constructor for one of my classes. Like the example shown below.
<img width="439" alt="Screenshot 2022-03-31 at 10 44 49 AM" src="https://user-images.githubusercontent.com/97585353/160965782-8de52433-6cfc-4986-8793-8becfd470d87.png">

Maybe you might have done the same thing too :/

**Comment by LauWyeRock** [comment]
i don't think the error is from the chunk you sent?

**Comment by seanpbteo** [comment]
> Hi! I had this problem too! For me I realised that it was because I initialized my field outside of the constructor for one of my classes. Like the example shown below. But I'm not sure as to why it would result in the same codecrunch error that you got. <img alt="Screenshot 2022-03-31 at 10 44 49 AM" width="439" src="https://user-images.githubusercontent.com/97585353/160965782-8de52433-6cfc-4986-8793-8becfd470d87.png">
> 
> Maybe you might have done the same thing too :/

Ah ok yep, I had the same problem! Thanks for the help @LohYangXian :)
