### ISSUE TITLE
Warning: uncheked method invocation

### ISSUE THREAD

**Issue by jingyulim1** [nus-cs2030/2122-s2#20]
# Summary

I am able to clear all the test cases/checks on code crunch but I came across this warning (uncheked method invocation) when attempting lab01.

## Description:

From google, this error seems to be due to not declearing the type for the List. But i used List "Point"in my method. Do anyone have any idea what this is about? 

## Code Snippets

![image](https://user-images.githubusercontent.com/95527957/151552906-2342250c-0560-4fb2-b010-82f1a009c844.png)

## Screenshots
![image](https://user-images.githubusercontent.com/95527957/151552661-1d5f4f97-55a9-4418-a927-f25413e30ba7.png)

Thank you.

**Comment by calvinseptyanto** [comment]
I think for your test case
You should change
List points = List.of(new Point(0, 0), new Point(1, 0))
to this
List<Point> points = List.of(new Point(0, 0), new Point(1, 0))

Becasue findMaxDiscCoverage can only accept <Point> list

**Comment by jingyulim1** [comment]
Thank you!

**Comment by snoidetx** [comment]
Hi @jingyulim1 ! Yes you should follow what @calvinseptyanto said to write this method.

What I want to highlight to you is the cause of this **warning**. As you know, the `maxDiscCoverage()` method takes in a Point list. In JShell you are trying to pass `points` to the method, and `points` is previously declared as `List` but not `List<Point>`. In that case, since `points` is still a list, Java will try to infer what type of objects is in the list, so it will try to run the method but it does not whether there could be an error because they may infer wrongly. That is why they send you a warning.

You will learn more about this in the Java Generics lecture on around Week 6.

**Comment by jingyulim1** [comment]
Understood, thank you!
