### ISSUE TITLE
Ways to check if my gameOfLife() is correct?

### ISSUE THREAD

**Issue by micaellaa** [nus-cs2030/2122-s2#206]
# Summary
Does anyone know of any way to check if the UnaryOperator I’ve created is correct without yet creating gameOfLife(…)?

## Description:
Currently stuck at the juncture between creating generateRule() and creating gameOfLife(…). Was thinking there must be a method in some Stream's API/List’s API that could take in my UnaryOperator so I can test before proceeding but couldn't find anything. Just did not wanna find myself with a wrong generateRule() and on the wrong track for gameOfLife(…) or something similar during a PE.

**Comment by eesung00** [comment]
U can assign your generate rule by UnaryOperator<List<Integer>> f = Main.generateRule(). Then create a sample list and run f.apply(list) and see if the result meets the situation for next generation.

**Comment by Swagston20** [comment]
Create a list of numbers provided by them and test

**Comment by SoSimplySean** [comment]
Just adding on to what @eesung00 mentioned, the reason you can use the `apply()` method is because the [UnaryOperator](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/function/UnaryOperator.html) interface extends the [Function](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/function/Function.html) interface. That's where the apply() method is coming from.

**Comment by jeanyeeee** [comment]
Adding on to @eesung00, You can do something like this (copy and paste)
`/open Main.java`
```
UnaryOperator<List<Integer>> f = Main.generateRule()
List<Integer> list = List.of(0,0,0,0,1,0,0,0,0)
f.apply(list)
```
Make sure that your `generateRule() `
`.collect(Collectors.generateRule() toList())`, to create a List of Integers !
