### ISSUE TITLE
Is there an @Overload tag in java just like @Override? 

### ISSUE THREAD

**Issue by DikshantDulal** [nus-cs2030/2122-s2#211]
# Summary
I cannot overload my tick method in lab07 level 3 in the following manner.  I don't understand why. 

## Screenshots

Screenshots (if any)
<img width="540" alt="Screenshot 2022-04-03 at 1 04 00 PM" src="https://user-images.githubusercontent.com/73227786/161412412-61769467-3b41-44a8-9c8a-03d5015eb962.png">

**Comment by yizziepeasy** [comment]
Sorry, is this Lab 8? And I don't think you need to declare that it is an overload method because it is taking two different inputs?

**Comment by SoSimplySean** [comment]
Don't believe there's an @Overload annotation. Overloading should already be a given once you have multiple methods with the same name and different parameters - not necessary to declare with the annotation. In this case, your `tick()` is already overloaded since you have different parameters (ie. function and action).

Think the only reason why we use the @Override annotation is to catch errors at compile-time if we aren't actually overloading any superclass method and just for readability.

**Comment by morksen123** [comment]
Remove the Overload tag

**Comment by alwinngjw** [comment]
Hi, I don't think that there is a @Overload tag, and I think it's not needed too. As long as the method signature (what the method takes in inside the parameter) is unique, the compiler will know it is an overloaded method and will know which method to call given the specific input by the user. 

Removing the @Overload tag should solve your issue.

Hope this helps.
