### ISSUE TITLE
Lab 08 Level 4: Issue with output after .tick()

### ISSUE THREAD

**Issue by lyjm21** [nus-cs2030/2122-s2#246]
# Summary

Unable to pass the test cases involving a .tick().tick(takeSword).tick(killTroll).

## Description:

Hi, I'm currently stuck at level 4, where i have passed the test cases except for those involving the .tick() method at the front. When I tried manually cases with .tick().tick(takeSword) and .tick().tick(killTroll), they all have the desired output. However when i do .tick().tick(takeSword).tick(killTroll), the following appears:

<img width="976" alt="Screenshot 2022-04-05 at 5 44 30 PM" src="https://user-images.githubusercontent.com/100070009/161727206-c834047b-326f-437c-b38e-ab32c37de451.png">

## Code Snippets

My code is as follows:

From actions.jsh
<img width="743" alt="Screenshot 2022-04-05 at 5 47 14 PM" src="https://user-images.githubusercontent.com/100070009/161727356-2e37e9fb-ffdc-4ccd-8173-6ffe2645eed3.png">

From room.java
<img width="710" alt="Screenshot 2022-04-05 at 5 48 08 PM" src="https://user-images.githubusercontent.com/100070009/161727502-5c141733-90d6-44cc-9a1b-88b54b7714c7.png">

Is there anything important i am missing out on? I understand that when I do the takeSword action, I must "update" the equipped status of the sword, which works and returns true when i do .tick().tick(takeSword), but it seems to return back to false after I do .tick(killTroll).  It seems like the tick() at the front messes things up, but I'm not too sure why.

**Comment by jonyeokj** [comment]
In your killTrollHelper in actions.jsh, I'm not exactly sure where the issue is but it might be because when you are modifying the list while iterating through it. Also, you should check for whether the troll and sword are present separately, because you don't have a situation whereby there is no troll present.

For your Room.java, I don't know how you are constructing your Things, but you should add an "age"/"state" attribute to your things and a method within these classes to modify this attribute when you call tick() in the room. Currently, it looks like you are saving the time in the room, which shouldn't be the case because a new Thing introduced to the room shouldn't be affected by the time already passed in the room.

You should create an interface to describe what these classes do, so it'll make tick() easier to define. Moreover, if you want to introduce new items in the future not mentioned in the lab, it'll be easier to implement these items because of your existing interface, and you wouldn't need to change the tick() method in your class.

This is my own example for the tick method in the Room class:
`Room tick() {
    return new Room(this, this.objects.map(x -> x.tick()))`
