### ISSUE TITLE
Lab 8 Level 3

### ISSUE THREAD

**Issue by jonyeokj** [nus-cs2030/2122-s2#250]
Hello, I am currently struggling with takeSword and how to define it. How should calling the method affect the state change in the Sword class? Also, how do I make the lambda expression only print one statement and not multiple at once, even thought the tick method will call the takeSword method multiple times (depending on how many objects there are in the room)?

**Comment by kaitlyngoh** [comment]
i think it may help for you to define a helper function for takeSword which takes in a room and outputs a new room (which contains the updated state of the sword). You can update the state of the sword to identify that it has already been taken, then add the updated sword to the new room you are returning and also make use of System.out.println() to print the statements

**Comment by adityajirafe** [comment]
Hey I think you can try to store a boolean in ur sword class to say whether its taken or not. As for the tick method calling takeSword multiple times, I don't think that's true(?) it doesn't call the takeSword method repeatedly, but only once for each time its mentioned in the jshell input code

**Comment by rexlionz** [comment]
hi, I would say it would be helpful to have if else statements in your takeSword to keep track of which statement is printed wrt the conditions in the room

**Comment by alwinngjw** [comment]
Hi, you can add a boolean method inside your Sword class to return the status of the sword (whether it is taken or not).

i have a similar idea to @rexlionz , where my takeSword have multiple if/else statements to check for the different conditions and print out the correct message.

Hope this helps

**Comment by junbin-tan** [comment]
Hey @jonyeokj 

I actually got stuck at level 3 as well, you might want to take a look at this thread. It contains quite alot of info and is a good place to start looking if youre still stuck!

[https://github.com/nus-cs2030/2122-s2/issues/202](url)

Hope it helps!

**Comment by nanfang02** [comment]
Hiii i think can add a boolean isTaken() into Sword class to check if the sword is taken or not. 
There are many conditions so it would be good to draw out a tree diagram to have a clearer understanding. 
The conditions include: 
if there is no sword ... 
if there is sword -> if sword is taken 
if there is sword -> if sword is not taken

**Comment by Zhenyubbx** [comment]
Yeap i also agree with nanfang02 because thats what i did and it works! Do check that the item is a sword before using the isTaken() method too!

**Comment by tristky** [comment]
Hi Jon, i think this can be attributed to Since events are associated with customers and the shop associated with the servers, a particular instance of the simulation can be completely defined by the priority queue of events, as well as the status of the shop. Write the class Simulate2 with a constructor that takes in the number of servers, together with a List<Double> of customer arrival times, and constructs a priority queue of EventStub events using the arrival time as the event time, and the status of the shop.

Include a run method within the Simulator2 class that takes no arguments, such that invoking the method will cause the simulation to start by having the events in the priority queue polled one after another until the queue is empty. The run method should return a string.

Hope this helps!
