### ISSUE TITLE
add() + poll()

### ISSUE THREAD

**Issue by gypsyxx** [nus-cs2030/2122-s2#258]
I wanted to implement my PQ using ImList at first but I realised in the JAVA API that priority queue has both the add and poll methods already. However, both methods are mutable, but how can I access the arrays without using ImList to make it immutable?

**Comment by TohDeKai** [comment]
Hello, I'm assuming you're talking about the project?

The PQ class can have a private final PriorityQueue that is already in the JAVA API. It works the same way as a ImList, whereby there is a private final List as a property.

**Comment by gypsyxx** [comment]
hi @TohDeKai so basically the private final List is a property of PriorityQueue or do I still need to create an ImList for PQ?

**Comment by TohDeKai** [comment]
> hi @TohDeKai so basically the private final List is a property of PriorityQueue or do I still need to create an ImList for PQ?

PQ refers the the class you are creating yourself whereas [PriorityQueue is a class in the Java API ](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/PriorityQueue.html). I've attached a link to the docs as well.

So within the PQ, there is a property that is private final and of the type PriorityQueue. Within the PQ, there is no ImList or List or anything like that, I'm saying that ImList and PQ will work the same way whereby they will have a private final property of a mutable type so that the ImList and PQ themselves will be immutable. 

Hope that makes sense to you

**Comment by gypsyxx** [comment]
@TohDeKai ok thank you so much for the clarification!
