### ISSUE TITLE
Why can't we use protected final in Loader so that we can inherit the attributes for recycled loader?

### ISSUE THREAD

**Issue by Swagston20** [nus-cs2030/2122-s2#27]

**Comment by szeying02** [comment]
The attributes can be `super()` into `RecycledLoader` even if you use `private final`. Furthermore, I believe that we defined the getter methods to access these attributes in the sub-class `RecycledLoader`, so there really isn't a need to use protected final. It's also possible that codecrunch would automatically reject all non- `private final` attributes (part of CS2030 scope I think, I'm not too sure on this).

**Comment by Swagston20** [comment]
Thanks, I know what you said can be done. But why not make life easier and use protected final so that the sub class can access. I just want to know the rational in encouraging us to not use protected final

**Comment by jingyulim1** [comment]
I think it is to strictly maintain the abstraction barrier. In case we have more subclasses in the future and we may not want the other subclasses to be able to access the information. Also, if we directly use the attribute from loader, if we were to change the representation in loader, then we may have to make neccessary changes everywhere else too.

**Comment by haoyangw** [comment]
For me I think it's cos the attributes in Loader are associated/shared with all Loaders, not just any specific subclass like RecycleLoader? So by restricting us to private final in the superclass `Loader`, this reminds us to declare e.g. `Loader loader = new RecycleLoader()` instead of `RecycleLoader recycleLoader = new RecycleLoader()` if we are trying to access shared attributes, and declare `RecycleLoader recycleLoader = new RecycleLoader()` instead if we want to access the extended variables and methods (only) RecycleLoader provides(but Loader doesn't)?

This kind of sounds like Dependency Inversion Principle in a sense, cos you depend on the superclass Loader wherever possible instead of depending on RecycleLoader directly

**Comment by undeser** [comment]
It is to maintain the Abstraction Barrier. 
Personally, it is a habit of mine to create getter functions, that way I can "legally" refer to the private attributes.
