### ISSUE TITLE
Project Level 7 Test 3 

### ISSUE THREAD

**Issue by wzs02** [nus-cs2030/2122-s2#303]
# Summary
Hi, does anyone now what this test case is supposed to check? The simulation in this test case seems to be similar to the earlier 2 tests, but for some reason the correct output is very different and I've checked my code but I can't seem to pass it. Would appreciate some help to clear my blind spot, thank you!

## Screenshots (if any): 
![Screenshot 2022-04-12 at 11 13 42 AM](https://user-images.githubusercontent.com/79785001/162872341-4e776553-2c07-4153-a272-9c715c1f8b5a.png)

**Comment by daitenshionyan** [comment]
I think your Server's queue size is only reduced when it is available to serve again (after resting). This might have caused Customer 3 to leave while Server 1 is still resting as its queue is still maxed out while it is resting.

Here are the magic numbers I used to produce similar results:
```
2 1 5 1.0
0.0000
0.3140
1.2050
2.7760
3.8770
0.3140
0.1030
0.7000
0.0014
1.0000
```

Result is similar to code crunch from lines 5 to 15 in your SS

**Comment by daitenshionyan** [comment]
Customers are allowed to wait at resting Servers so long as their queue is not maxed out. For test7_2, Customer 3 went to 2 because Customers prioritise the Servers that are able to serve them immidiately. So since Server 1 is resting and not available, Customer 3 will go to 2 that is available.

So for the third test, when Customer 3 arrives it will wait at Server 1, with an empty queue, and stare at it until its break is over.

**Comment by wzs02** [comment]
@daitenshionyan THANKS SO MUCH! This was the fix I really needed :)
