### ISSUE TITLE
Level 4 hidden test case

### ISSUE THREAD

**Issue by ddeung0302** [nus-cs2030/2122-s2#342]
I have got a hidden test case and not sure why it does not work with these particular cases.  Did any one get the same error as me? 
<img width="433" alt="Screenshot 2022-04-16 at 8 14 47 AM" src="https://user-images.githubusercontent.com/100173663/163654346-2b35361b-9817-4c9b-9ea4-faf5e1414da2.png">

This is my tick for Room.
<img width="423" alt="Screenshot 2022-04-16 at 8 22 40 AM" src="https://user-images.githubusercontent.com/100173663/163654465-df41cca1-68a7-4903-a0f0-4783569ed0a3.png">

This is my get for Troll used in tick. I've already defined last as private static integer 4.
<img width="219" alt="Screenshot 2022-04-16 at 8 21 44 AM" src="https://user-images.githubusercontent.com/100173663/163654436-344bd0c8-3be5-4eb8-9b63-0baf7b3fd8d3.png">

**Comment by herq-ules** [comment]
not very sure but it could be because for every thing you are using .get(next) to get the next state where next is defined using this.time + 1. i think if sword was added first (room.time = 1), then .tick() (room.time = 2), and then troll was added (when room.time = 2), when you .get(next) for your troll, the state of the troll would more than it should be (since you would have used .get(3) instead of .get(2))?

**Comment by jamietan123** [comment]
i think you can try changing the value of n

**Comment by ddeung0302** [comment]
Thank you for your help! I got it sorted
