### ISSUE TITLE
Level 7 wrong timings

### ISSUE THREAD

**Issue by TohZhanTing** [nus-cs2030/2122-s2#375]
# Summary
Put a summary of the question

## Description 
Using the same concept as Level 5 which I call supplier.get only in serve event, and have updated the rest timing in the server. 
E.g. new Server(...super.getTime() + super.getCust().getServiceTime() + server.getRestTimes()...)
I had made some adjustments to WAIT event as well, however, i still doesnt get the correct timings.
May need some advise from all, thanks

## Screenshots (if any): 
Insert Images here if necessary
<img width="457" alt="Screenshot 2022-04-18 at 1 02 08 PM" src="https://user-images.githubusercontent.com/103926448/163791968-47d161f2-3dbb-40f7-9e0a-1c66ed0bf762.png">

**Comment by loqir** [comment]
im facing this issue as well, after getting the rest time in the done event, i updated my server and added the rest time to his next available time but the output is still the same

**Comment by jamietan123** [comment]
I thinkit could be because your next event takes the server linked to the previous event and not the updated server

**Comment by LohYangXian** [comment]
I think the servers in your shop is not updated properly like what @jamietan123 said. You can try to overwrite the shop  yourself so that it calls the correct next available time from the server :)

**Comment by TohZhanTing** [comment]
<img width="528" alt="Screenshot 2022-04-18 at 8 15 24 PM" src="https://user-images.githubusercontent.com/103926448/163806957-f4296bce-e6a6-458e-9169-cd1eefce3734.png">

@LohYangXian @jamietan123 
Hi all, i think the rest time for server 1 is "stolen" by server 2, resulting in the issues above. Any advice to remedy it? thanks

**Comment by eesung00** [comment]
Hi, just to share my experience, I faced the "stolen" issue before is because in the simulate code, I accidentally "execute" twice for each event in every the loop. You might want to check if you execute the correct times in simulate.java?

**Comment by rachtan27** [comment]
> im facing this issue as well, after getting the rest time in the done event, i updated my server and added the rest time to his next available time but the output is still the same

Hi Im facing the same issue as you but i believe the reason why the output is the same is because the Serve event is added to the Priority queue before the Done event is executed, hence the Serve event does not account for the rest time.... but I am still unable to find a solution for this so far... does anyone have any idea on how I can go about solving this please?
i saw another post previously which mentioned that they solved qns7 by handling the resttime in simulate7 and creating a new PQ in simulate7... is there any other method apart from that since i passe the supplier into Server instead?

**Comment by ngnevan1** [comment]
I faced the issue in the original post too because I used a pendingServe implementation as described in #153 which added the serve event before the server was done serving and thus was unable to check if the server was resting. What I did to solve this was to create another event CheckServer in between the pendingServe and Serve events. 

The CheckServer event would 
1. Get the updated server from the shop 
2. Check if the server is resting 
3. If server is resting, create a new Serve event with the updated time
4. If not create a serve event with the existing time

**Comment by TohZhanTing** [comment]
Thanks guys for the advices! I've managed to solve the issue by having a boolean on whether the server is done serving. By doing so, i've ensured that for customers in the waiting list will only be served after each event is done. Thanks!

**Comment by terrrence** [comment]
> # Summary
> Put a summary of the question
> 
> ## Description
> Using the same concept as Level 5 which I call supplier.get only in serve event, and have updated the rest timing in the server. E.g. new Server(...super.getTime() + super.getCust().getServiceTime() + server.getRestTimes()...) I had made some adjustments to WAIT event as well, however, i still doesnt get the correct timings. May need some advise from all, thanks
> 
> ## Screenshots (if any):
> Insert Images here if necessary <img alt="Screenshot 2022-04-18 at 1 02 08 PM" width="457" src="https://user-images.githubusercontent.com/103926448/163791968-47d161f2-3dbb-40f7-9e0a-1c66ed0bf762.png">

hi! can i ask how did you resolve this issue? im currently facing this issue now and it seems that my servers are never going into the rest event even though i updated the states of the shop and servers
