### ISSUE TITLE
Project Level 4

### ISSUE THREAD

**Issue by lyjm21** [nus-cs2030/2122-s2#377]
# Summary
Hi, I am currently stuck on the implementation of the statistics. If I am not wrong, we are supposed to modify simulate3 and basically replace the "end of simulation" string to the statistics. For every next event that comes in i understand that it is wrapped around an optional, so I have tried to use filter and ifpresent to check if the next event that comes in is wait serve or leave to add to the respective counters, but i am faced w a lot of errors.  

## Description 
Is my understanding correct or is there a simpler way to do it? Upon testing my run seems to not be able to compile. 
<img width="947" alt="Screenshot 2022-04-18 at 7 11 33 PM" src="https://user-images.githubusercontent.com/100070009/163800431-76223845-a594-41b1-b185-18aa870f8b07.png">

I tried taking out the wait method and testing w just the counters at first, but my run comes up w this error in jshell. 
<img width="729" alt="Screenshot 2022-04-18 at 7 10 25 PM" src="https://user-images.githubusercontent.com/100070009/163800446-2c7d923a-13b6-47cd-9361-d65eb5b80a4e.png">

## Screenshots (if any): 
Here is my run code for simulate4
<img width="913" alt="Screenshot 2022-04-18 at 7 14 20 PM" src="https://user-images.githubusercontent.com/100070009/163800568-f821a1fd-75cf-47cc-88b0-f2fe6acc6091.png">

**Comment by WenJett** [comment]
Hello,

Generally modifying variables within the lambda function would just lead to a compilation error, but your idea is correct. 
Since you have declared orElseThrow() within your code, that is why you are getting that NoSuchErrorException, as such I presume after your "LEAVE" event or "Done" event itself for example, there wouldn't be any next event and led to an occurrence of the exception. 

Actually when u implement next.first().filter() you are already filtering it to the event you want, so you do not actually need to check isPresent() and instead could implement map() with a helper function to get what you want and add it to the counter you have.

**Comment by summerthia02** [comment]
for me, since the wait event and serve event is what is crucial for this level, I created an isWait and isServe function in all the events and return true for wait and serve event respectively, and false for others. 
then in the simulate4, you can then see if this event is either a wait or serve event, and do the respective calculations - so I dun think map is required here!

**Comment by fionlim** [comment]
I think a neater way to do this is to create a Statistics class, with attributes that store serve/done events and leave events separately. you can then define a function to calculate the mean wait times, whereby for each wait time you take the serve time - arrival time, and the toString method prints out the required statistics in your simulation!

**Comment by weihan10** [comment]
It's better to create a Statistic class as mentioned above, with certain methods like addLeft(), addServed() and addTime() which each increment the number of customers leaving, being served and time spend watiting respectively such that you achieve a better code design.

**Comment by lyjm21** [comment]
Thanks so much for the helpful comments! Slipped my mind that I should just check the current event itself instead of the next one which is wrapped in the optional.
