### ISSUE TITLE
More than necessary service times provided

### ISSUE THREAD

**Issue by elvern18** [nus-cs2030/2122-s2#386]
![image_2022-04-19_04-56-53](https://user-images.githubusercontent.com/77615600/163877075-b806286a-7d1d-428e-bfff-8212bd696bae.png)

How do I only read the necessary values of service time ?

**Comment by Seibell** [comment]
Hi, you can use the Lazy class to cache the service times, for me my customer has an attribute Lazy<Double> serviceTimes, where i will only call customer.getServiceTimes().get() when needed in the serve class.

**Comment by bryankwe** [comment]
Since some customers may leave, you do not call get() for these customers. What I did was to only call get() for customers in my Serve event to obtain their actual serve time. 

Lazy class caches the customer's serving time in that, for the second and subsequent times you call get() for that customer, it doesn't call the supplier's get() but instead the cached value in the Lazy class.

**Comment by feederalert** [comment]
I agree with the comments above. Remember to only call get() when the customer is served (rather than when they start waiting) or your customer serve times will be all over the place.

**Comment by jamietan123** [comment]
^ yup dont call service time when its waiting

**Comment by weihan10** [comment]
> Since some customers may leave, you do not call get() for these customers. What I did was to only call get() for customers in my Serve event to obtain their actual serve time.
> 
> Lazy class caches the customer's serving time in that, for the second and subsequent times you call get() for that customer, it doesn't call the supplier's get() but instead the cached value in the Lazy class.

Just to add to this method, you can try calling only when it's a ServeEvent in the Simulate class like I did. Reduces code complexities and a cleaner code.
However depends on how you would like your design to be like.

**Comment by weihan10** [comment]
> > Since some customers may leave, you do not call get() for these customers. What I did was to only call get() for customers in my Serve event to obtain their actual serve time.
> > Lazy class caches the customer's serving time in that, for the second and subsequent times you call get() for that customer, it doesn't call the supplier's get() but instead the cached value in the Lazy class.
> 
> Just to add to this method, you can try calling only when it's a ServeEvent in the Simulate class like I did. Reduces code complexities, dependencies on other classes and gives a cleaner code. However depends on how you would like your design to be like.

**Comment by summerthia02** [comment]
only call the service times when its needed (in the serve event only) , thus use lazy evaluation

**Comment by yjjjiajie** [comment]
you can just assume that the number of service times provided are correct, as long as you call .get() in ServedEvent, it will be automatically settled. for me, I wrote it in my Simulate as well. When the event is Served, I will then call .get() to get the right duration. You can then "update" the event so that the customer's new duration will be reflected.

**Comment by jlee1007** [comment]
you can just assume its the same as the previous level i guess

**Comment by Lu-Yi-Fan** [comment]
only evaluate when its the serve event

**Comment by hiimss** [comment]
Adding on, if I am not wrong, the reason why the Lazy class is given and suggested as above is due to the passing by reference. I thought of it as the value being cached in the Lazy class and when you call get(), it will return the respective service time for each customer, hence it has to be called appropriately or it will mess up the times
