### ISSUE TITLE
Level 3 order wrong, tried accounting for it in EventComparator but still no change to output

### ISSUE THREAD

**Issue by joannelxl** [nus-cs2030/2122-s2#388]
# Summary
Hi! In level 3, I had the problem where if there are 2 customers of the same timing (1.500 2 serves by 1 and 
1.500 1 is done serving by 1), the order of polling is wrong (customer 2 is polled before customer 1). I went to change my  EventComparator class to account for it but it seems like the polling is still in the wrong order. Does anybody have any idea on how to fix this?

## Screenshots (if any): 
Here is my output:  I think the reason why the last print statement is wrong is due to the wrong order of polling,  hence if I am able to solve this, it should be able to work.
![image](https://user-images.githubusercontent.com/79855907/163922941-27279943-eb39-47b2-ab5c-6b3748f2a074.png)
EventComparator Class:
![image](https://user-images.githubusercontent.com/79855907/163922877-412d2da9-4c49-4832-9ba9-fb361fe7acf8.png)

**Comment by pearlynliu** [comment]
hi! your eventcomparator seems fine. maybe you might want to check out where the server with id of -1 is created? i think there might be an error in your Wait, Serve or Done events, depending on how you implemented them. 

you can also check whether the waiting customer is being served by the same server it is queuing at. 
for me, for the wait, serve and done events, i looped through the shop in the execute method, and took the server with the same id as this.server.getId(), instead of directly using this.server in those 3 events. this is to make sure that all changes to the server are taken into account since this.server might not be fully updated. 

i hope this helps!!

**Comment by joannelxl** [comment]
hi pearlyn! thank you for replying :) I just solved it ! it turns out that i did not initialise my PQ with the comparator in the PQ class... haha
