### ISSUE TITLE
Can't solve Level 3_2 after change in implementation for Level 6

### ISSUE THREAD

**Issue by sheryew** [nus-cs2030/2122-s2#389]
1.500 4 arrives
1.500 4 waits at 1
TRYTOSERVE21.5
1.500 2 serves by 1

Why is it that my arrives appear before my serves? 
Anybody faces a similar issue?

**Comment by michael192002** [comment]
For me, in order to preserve the correct order of events, I tried to assign an attribute to each event that specifies the priority level (e.g. serves should prioritized over arrives), and used the priority level in the comparator to order poll events correctly from the PQ. I'm not sure if it is the best way to do so, but in my case it works just fine. Hope it helps!

**Comment by Guanjung27** [comment]
you can include comparison of customerID in your EventComparator when there is a tie in event time

**Comment by sherylau** [comment]
in my eventcomparator when both events have the same event time, i checked the customerID to make sure that the customer with a smaller customerID comes first

**Comment by sheryew** [comment]
Thanks everybody for your help! I managed to solve it.
