### ISSUE TITLE
Level 3 - Time factor in invoking WAIT events

### ISSUE THREAD

**Issue by t11-20** [nus-cs2030/2122-s2#394]
Hi all, I am current stuck on level 3 where I am unsure of how I could implement the WAIT event, such that when servers are full (1 serving, 1 queuing), the next arriving customer will leave.

My current implementation is as follows: 

1. Take in number of servers, list of arrival times (as stated in the qn)
2. Create shops based on number of servers, ARRIVE events based on arrival times
3. For the execute in ARRIVE, for each server, it will check if it is able to serve (I have 2 optional<Customer> in serve, if one is occupied, it will trigger WAIT, else it will trigger SERVE). If both optional<Customer> are occupied, the next arriving customer will leave.

4. After the customer is served, a DONE event will be invoked. When it is done, the optional<Customer> in serve will become empty again. 
5. The WAIT event will trigger, and it will invoke the SERVE event, then DONE event.

My issue now spans from the WAIT. I did not implement any time checking in my program. I am met with the issue, whereby, when my SERVE event is done, it becomes optional<Customer> empty(), then the waiting customer will become the serving one.

However, at this point, if a third customer comes in, it will trigger the WAIT event, instead of LEAVE. As shown below:

![TimeExcluded](https://user-images.githubusercontent.com/101245687/163937538-e47541a1-b5b5-4d86-8698-2f01647ed909.jpg)

Hence, I am unsure on how I can implement the timing in this. Like, if I were to put something like customerArrivalTime < nextAvailableTime for server, all the arriving customers (aside from the first customer), will all leave. As shown below:

![TimeIncluded](https://user-images.githubusercontent.com/101245687/163937593-63ca239b-7562-43d6-b3a4-ba8900db8464.jpg)

May I ask what is the pseudocode behind implementing level 3 as a whole? Any help would be greatly appreciated! Thank you

**Comment by kkinmunn** [comment]
Rather than having Optionals, do you think that creating an `ImList<Customer>` might be more efficient? (In Level 6, there is a maximum queue length i.e. in 6.1 its 10, so do you feel creating 10 Optionals by then will be feasible?) Perhaps you can think of storing the customers in queue into an ImList in your Wait class, and remove the customer that is done served from your ImList in your Done class - in this way, you can implement some checks to see whether can the next Customer wait or does the next Customer leave based on your ImList. Alternatively (or even in addition to), you can create boolean variables for your Server to see if they can serve or they can allow customers to wait too!

From the task description, 
ARRIVE → SERVE → DONE
ARRIVE → WAIT → SERVE → DONE
ARRIVE → LEAVE

In your Arrive event, you might want to check if Server is available, if yes, return a Serve event, else if check whether Server allows customer to wait, if yes, return a Wait event, else return a Leave event. Hope this helps!

**Comment by WenJett** [comment]
Hello,

It would be easier for you by implementing ImList<Customer> in the server to keep track of whether the server is free to serve and whether the new customer can wait for the server depending on the size of the ImList. This will ease your modification in the future levels as well. 

You could also add in an additional property in the server to see if the server is free to serve, which would allow you to determine whether the new customer coming in can go to SERVE event directly or instead should go to WAIT event.

**Comment by t11-20** [comment]
@kkinmunn @WenJett Thank you for the explanation! Initially, I tried to implement ImList<Customers> in my Server class. However, I was unsure of how to check whether 
1. Server is available
2. Server is able to wait

May I ask, what's the algorithm associated with the checks using ImList<Customer>?

**Comment by WenJett** [comment]
Hello, 

To check whether the Server is available or not, I have an additional boolean property (freeToServe) in Server which is true initially and becomes false if the Server is serving a customer. So after the Done event, the server becomes freeToServe again. 

To see if the customer is able to wait at that server, u can just check based on size() of the ImList of customers and have a int property (maxQueueSize) to be 1 (this will be changed in subsequent levels based on the input).  As long as the size of the ImList is still less than the maxQueueSize, you can allow the customer to wait at that server. 

Hope this clarifies your doubts!

**Comment by t11-20** [comment]
@WenJett thank you very much for the explanation! I think I get it, will try to implement it now! :D

**Comment by t11-20** [comment]
@WenJett @kkinmunn Thank you both! I kind of managed to solve it, although idk if my implementation is correct, but I managed to pass level 3 test cases!
