### ISSUE TITLE
Level 7_3 Index error

### ISSUE THREAD

**Issue by kkennyllow** [nus-cs2030/2122-s2#398]
Hi, my code passes 7_2, however it fails on 7_3 with the following error. 

![image](https://user-images.githubusercontent.com/99718568/163961698-205b09ae-aa06-4ae6-8917-7fbd1672c5ff.png)

My current implementation is that:
Whenever the event is a DoneEvent, I will iterate through the current PQ, looking for any ServeEvents with the same Server, and update the eventTime and the respective Server nextAvailableTime. After that, during execution of DoneEvent, I will update the Server nextAvailableTime too.

However, when I set the probability of a server resting to anything above 0.74, it returns the following error: 

![image](https://user-images.githubusercontent.com/99718568/163961482-0c7efa90-b6e3-4e38-93b2-7cf0fb6ceb83.png)

Anyone faced a similar problem? Or is there a better way to implement Level 7? Let me know if more information is needed. Thanks in advance!!

**Comment by weihan10** [comment]
Hi, I did a method that's basically identical to yours in the way I loop through all and add it in. It's hard to really pinpoint without seeing your loop, but from the error messages, it must be because the element does not exist in the list, that's why you get an index of -1 with the indexOf() method (it returns -1 if element does not exist). Did you use the indexOf() method?

**Comment by kkennyllow** [comment]
> Hi, I did a method that's basically identical to yours in the way I loop through all events and add it in. It's hard to really pinpoint without seeing your loop, but from the error messages, it must be because the element does not exist in the list, that's why you get an index of -1 with the indexOf() method (it returns -1 if element does not exist). Did you use the indexOf() method?

Hi Thanks very much Weihan, I managed to find the bug. :)
