### ISSUE TITLE
IndexOutOfBoundsException for Level 3

### ISSUE THREAD

**Issue by pwintthiri** [nus-cs2030/2122-s2#404]
Hi everyone, I used ImList to wrap around List<Server> for Shop to make it easier to modify the list of servers for the Events. But when I tried to run Simulate3, it gave an IndexOutOfBoundsException. I checked my code again but I can't seem to find where the Exception could come from. Has anyone had the same error? Thank you!

![Screenshot 2022-04-19 at 8 47 29 PM](https://user-images.githubusercontent.com/95198407/164007448-c35f3f11-ed35-4eff-a6ca-8312ed432c7b.png)

**Comment by andrea-yxl** [comment]
Hello! I previously faced this problem as well. For me, I ran into this error because I tried to get the index of my server in my ImList of servers by using the .indexOf() function and passed the index into my ImList set function. This threw me an error as my index returned me -1 which is an invalid index to be passed into the ImList set function. I managed to solve it by identifying the position of my server by its ID instead. I think you can check if the index you are passing into the set function is valid? Hope this helps!

**Comment by Brianliew77** [comment]
Hi, check if ur loop conditions are correct. Playing ard with the <= or < would likely solve this problem! If u dont mind uploading screenshots of ur code I can take a look at them

**Comment by jamietan123** [comment]
I think its quite specific to the methods that you call but it seems like its something to do with Serve

**Comment by pwintthiri** [comment]
> Hello! I previously faced this problem as well. For me, I ran into this error because I tried to get the index of my server in my ImList of servers by using the .indexOf() function and passed the index into my ImList set function. This threw me an error as my index returned me -1 which is an invalid index to be passed into the ImList set function. I managed to solve it by identifying the position of my server by its ID instead. I think you can check if the index you are passing into the set function is valid? Hope this helps!

Yup, I also used .indexOf() and I'm getting a -1 as well. I managed to solve it, thank you!

**Comment by pwintthiri** [comment]
I had to add 1 to .indexOf() at Serve to solve it, thanks everyone!
