### ISSUE TITLE
Project Level 8_4: self-check 3 not made available after done serving

### ISSUE THREAD

**Issue by seanpbteo** [nus-cs2030/2122-s2#408]
# Summary
Hello all, has anyone else run into the same problem for test case 8_4? it seems that my self-check 3 is unavailable and does not serve customer 12 after it is done serving customer 9.

I implemented self-check as an extension of Server and hence should retain the same functionality when being updated through the various execute methods. Thanks in advance!

## Screenshots (if any): 
<img width="609" alt="image" src="https://user-images.githubusercontent.com/99883397/164029100-d2779b2e-fc35-4be0-8d3a-f0638748c179.png">

**Comment by wjahoward** [comment]
for my selfcheckout server, after it has done serving the current customer, it will check if it has any waiting customers available. if have, it will serve the next latest waiting customer.

**Comment by Swagston20** [comment]
for self-check out, using the share queue, check which has the latest service timing and pass the serve to the serve event

**Comment by WenJett** [comment]
Hello,

It is likely your customer 12 & 13 which is waiting at self-check 2 is only waiting for self-check 2 to become available again. Since self-check shares one queue, these customer should wait for the next available self-check regardless if the serverID is the same as the one the customer is waiting at.

**Comment by Ohnojiso** [comment]
You can add some System.out.println(...) in between your code to check what actually is the cause to this problem. For me it seems like your Customer 12 and 13 is only waiting at SelfCheck2 while it should be all the SelfChecks. If this is the problem you can try to first check if this current server is a SelfCheck, if it is then you can retrieve all the SelfCheck from your Shop's server list and find the SelfCheck with the shortest "waiting time"(i.e. next available time), and use that SelfCheck instead of the one that you have returned from the previous event(which I assumed to be SelfCheck 2).

**Comment by StanleyMak** [comment]
you should have a check after every done event if there are any customers in the queue. if so, there should be a new serve event created.

**Comment by seanpbteo** [comment]
Thank you everyone! I realised that I didnt update my SelfCheckout to take serve the next SelfCheckout with the earliest done time so I iterated through my shop to find that server.
