### ISSUE TITLE
PROJECT LEVEL 4 STATS

### ISSUE THREAD

**Issue by Guanjung27** [nus-cs2030/2122-s2#417]
hi, can i just check if its compulsory to create a new statistics class to compute the stats?

**Comment by bryankwe** [comment]
This was what the question on CC wrote:
"Rather than changing the implementation details of the existing programs, try to create a Statistic object, and update this object as the events are polled from the priority queue."

So I guess since it will be good to have a Statistic class?
Imo I think it's also easier to deal with the statistics that way.

**Comment by lyjm21** [comment]
Hi Guanjung! Personally I did not do so, but I would highly recommend doing so to make your code more organised.

**Comment by wennwei** [comment]
I think its not necessary to create a new class but it would make your code neater. Personally I didn't but was still able to pass level 4.

**Comment by pwintthiri** [comment]
Hi Guanjung, I created a Statistic class but I think it's not compulsory since cc says "try to create a Statistic object"!

**Comment by jlee1007** [comment]
i created a class i think that really makes things neater & easier to follow & if I'm right u won't need to touch that class aft l4 so its much easier to build on!

**Comment by chorhanchean** [comment]
Hi, I did create the new Statistics class, I did not have to modify any of my previous codes, most of the work is done in Simulate 4 and Statistics.

**Comment by Zarilex09** [comment]
i think by creating a new class you are abiding by the single responsibility principle so it makes the code more clean and readable, as for do you need, it is not compulsory
