### ISSUE TITLE
Project Level 8 8_4 test case

### ISSUE THREAD

**Issue by ReganKvioke** [nus-cs2030/2122-s2#430]
![image](https://user-images.githubusercontent.com/92613467/164223565-6fe4f260-e6bf-4648-8b6f-cab82e1392e8.png)
Sorry for the trash quality, if udm can click it to see better.

Hi, I am wondering if any of you have the same problem above. So I have made a PENDING class such that WAIT -> PENDING -> SERVE. However, as you can see for 2 and 3 who are self-checkout servers, although the summation of the nextServerAvailable time is correct, the PENDING code created an infinite loop at PENDING 14 after "11 serves by 1".

Has anyone had these issues? Also, if yall don't mind sharing, how did you manage to output as self-check serverIndex?

**Comment by ngnevan1** [comment]
Hi I'm not very sure what's causing your infinite loop but it might be that your pending event is not getting an updated server from the shop but just using its own server when the pending event was created?

What I did to output the self-check as a self-check instead of a server was to create a `SelfCheck` class that extends from server that has it's own toString method and make sure that if any of the methods updates the server, if the object is a selfcheck it will create a new selfcheck instead of creating a new server.

**Comment by seanpbteo** [comment]
Hello, I ran into the same problem just now as well. What I did was to implement the same code chunk in my waitEvent as in pendingEvent such that the server passed into the next event is the updated selfCheck with the lowest done timing. Hope this helps!

**Comment by ReganKvioke** [comment]
@ngnevan1 @seanpbteo Yo thanks guys, it was just my dumb ass not assigning proper indexing
