### ISSUE TITLE
Level 7 Rest Times

### ISSUE THREAD

**Issue by nicljr** [nus-cs2030/2122-s2#456]
Hi guys,

For Level 7, for the Supplier of the Rest Times, I have defined it within my Server class as a variable. Whenever I call the Supplier for the Rest Times within the Server class, I keep on getting 0. Anyone can help on how to factor in the correct rest times from the supplier. Thanks!

**Comment by Geraldworks** [comment]
did you use the correct constructor to assign this.restTime = Supplier?

**Comment by Guanjung27** [comment]
dont use the Lazy interface if you are , it causes you to keep getting 0 probably

**Comment by celine-chung** [comment]
^ yup as GuanJung27 mentioned, if you store the rest time in a Lazy, it will call the first rest time which could be 0, cache the rest time, and subsequently when trying to get the rest time it will simply return the cached rest time of 0. instead, just leave it as a supplier so that every time you call it you get the next randomly generated number! and for ease of testing, you could probably try testing your getRestTime method in jshell first and run it multiple times to make sure that each time generates a new number:-)
