### ISSUE TITLE
Wrong output for Level 3

### ISSUE THREAD

**Issue by evewlim** [nus-cs2030/2122-s2#46]
hello! I'm getting the wrong output for this level and I'm not sure how I should fix my code

![image](https://user-images.githubusercontent.com/95474365/155386039-0eb600a5-adce-4ad3-a7c1-74ea55f47518.png)

**Comment by pearlynliu** [comment]
hi!! i think you may have compared waitingTime first instead of fare, it should be the other way around! compare the fare first, and if the difference in fare is zero, compare the waitingTime

**Comment by seanpbteo** [comment]
Hello! I failed the same test case but in compareTo, I compared if the fares were different and then if waitingTimes were different. Still not too sure how the error comes about

**Comment by jingyulim1** [comment]
You should check if you are using the correct request for the booking. I think there are good advices on this [thread ](https://github.com/nus-cs2030/2122-s2/issues/35) which you may find helpful.

**Comment by chloeoxe** [comment]
Yup, I agree with jingyu! Because I encountered the same problem as Sean and later realised that it was because I was comparing the same request (i.e. this.request) for both bookings. Then I amended my compareTo such that it was comparing this.request with other.request and it fixed the issue. Hope this helps!

**Comment by evewlim** [comment]
thanks everyone for your help!! i managed to find the error in my compareTo method and got the correct output :-)))
