### ISSUE TITLE
Level 7_3 

### ISSUE THREAD

**Issue by nicljr** [nus-cs2030/2122-s2#466]
I have passed Level 7_1 and 7_2 but I cant pass the Hidden test case 7_3, when I input the numbers into the Main Scanner class, It doesn't output anything. I assume this is a case of an Infinite Loop occurring within my classes. Any one experienced this before or have any idea how to get certain outputs to see where the infinite loop occur in my implementation? Thanks!

**Comment by adityajirafe** [comment]
hi, its a little difficult to know what your problem is without any more information about your implementation, but what I found particularly useful to solve my infinite loop errors was adding a system.out.println statement in my run method to print out the event (so that I can see exactly where it breaks, since your run method outputs a string, its kinda a print all or nothing situation). in addition, I modified the Server::toString method to display the state of the server, the customers waiting and any other useful information to make debugging a lot smoother. hope the tips help!

**Comment by Keefetgy** [comment]
What i would suggest is using System.out.println to output your priority queue and polled event to see exactly the event causing the loop. I would think that the event causing the infinite loop is most likely the Waiting event that is a recursive event. Also, you can try control-z to stop the infinite loop and scroll up to view the event causing the problem.

**Comment by nicljr** [comment]
Thanks guys for the help, just finished level 7! appreciate it!
