### ISSUE TITLE
test case 8_4 (Customer unable to wait at self check)

### ISSUE THREAD

**Issue by Lu-Yi-Fan** [nus-cs2030/2122-s2#474]
<img width="625" alt="Screenshot 2022-04-22 at 2 47 29 AM" src="https://user-images.githubusercontent.com/88626655/164532550-93e187ad-98a8-403a-b38d-cbfe2be7ae53.png">

Hi did anyone else face a similar issue where the customer is unable to wait at the self check out?

**Comment by lihuicham** [comment]
hi yi fan, do u mind telling me how you manage to print out the "self-check" ? 
for now, i have a SelfCheck that subclasses the Server. However, since it is a subclass, all SelfCheck are indeed Server, so when i do the identify() check, it keeps printing the Server class toString() instead of the SelfCheck one ...

any idea on how to do this ?

**Comment by Seibell** [comment]
@lihuicham you can create a pair<string, string> of self-check ids, then u add an if condition before each event is printed that checks if the string contains for example: "serves by " + selfcheckid, if so, then replace with "serves by self-check " + selfcheckid.
This was before i had to change my implementation due to some logic errors but this worked in printing out the self checks

**Comment by Seibell** [comment]
@Lu-Yi-Fan I think the issue is probably because you are not properly update each and every self-check counters queue at wait/serve events, maybe try printing out the queue stat for each self check at each event, this may help u find where the error in logic flow is

**Comment by Lu-Yi-Fan** [comment]
@Seibell i found my bug, i forgot to add all the wait events hence the mess up in timing and the positions of the events! Thank you

**Comment by Lu-Yi-Fan** [comment]
@lihuicham Hi i did not create a extra class to handle printing of the to strings, i handled this case by adding an attribute of a string with my server and when i want to call my server to string i check for the type of the server to return the appropriate string! hope this helps
<img width="453" alt="Screenshot 2022-04-22 at 12 39 37 PM" src="https://user-images.githubusercontent.com/88626655/164604286-065ab23b-9463-4241-8bef-26091f5a66f4.png">
!
