### ISSUE TITLE
Level 8 [order of customer for self check wrong]

### ISSUE THREAD

**Issue by Lu-Yi-Fan** [nus-cs2030/2122-s2#480]
<img width="704" alt="Screenshot 2022-04-22 at 12 42 11 PM" src="https://user-images.githubusercontent.com/88626655/164604572-85bb6bae-7ec6-4351-a2e5-931d723592d6.png">

Hi i still cant seem to solve my test case 8_4, the timing and everything is correct already but somehow customer 15 gets served before customer 14, did anyone face the same issue as well! Thank you!

**Comment by Guanjung27** [comment]
This could be due to not checking which self checkout counter might be available first while in your pending/waiting event, as a result you custoer 14 is always waiting for self-check 3 even tho self check 2 might be available at an earlier timing.

**Comment by abigailxj** [comment]
you can have a function within shop that gets the self checkout counter with the earliest avail time. then you can call this function in pending bc the self check server from Wait may not be == self check server it is actually served by

**Comment by sherrycqu** [comment]
Hi! Since all the self-check servers share the same queue, perhaps you should have a shared wait list for self check. Could you error be caused by the fact that the customers are allocated to the wrong self-check server? When you call a serve event from wait or a pending event, you should check which is the next earliest available self-check server. Similarly, when you return a pending event, you should update the server to be the next earliest available self-check server and the event time would be the available time of that server.
