### ISSUE TITLE
Still getting infinite loop for Test Case 6_2

### ISSUE THREAD

**Issue by lyjm21** [nus-cs2030/2122-s2#489]
# Summary
Infinite loop for test case 6_2 

## Description 
Basically my code runs something like this:
ARRIVE -> WAIT -> WAITING -> SERVE/WAITING(will go to SERVE once possible) -> LEAVE

However, I realise that no matter how i modify my code, such as updating the shop for every step, removing the placing of customer into queue from WAIT to WAITING, I am still stuck at this problem. I have read the other issues raised here but I am still stuck after close to 2 days ://. I suspect it has something to do w my if conditions but after I put System.out.print I realise that for my waiting queue, I will never get the desired customer I want resulting in infinite loop, and my customer 10 just seems to magically disappear every time.  Overall I am very confused w what's wrong. 

To explain my code as accurately as I can understand, from ARRIVE to WAIT, i place the customer in the waiting queue, then i move on to WAITING regardless. At WAITING, if the first customer in the queue matches, it goes to SERVE, otherwise it goes to WAITING again. It seems that regardless, I will always go to WAITING. 

## Screenshots (if any): 
WAIT execute:
![Screenshot 2022-04-22 at 3 42 25 PM](https://user-images.githubusercontent.com/100070009/164636966-cb2d8306-87e0-48ba-8466-b3ce52e68d68.png)

WAITING execute:
![Screenshot 2022-04-22 at 3 42 38 PM](https://user-images.githubusercontent.com/100070009/164637368-f3d0e3c3-1650-4b97-8b92-c744efab834d.png)

The loop:
<img width="354" alt="Screenshot 2022-04-22 at 3 46 11 PM" src="https://user-images.githubusercontent.com/100070009/164639087-1993a913-58a8-49b0-b0a6-95d6287a79af.png">

**Comment by ReganKvioke** [comment]
Maybe in your Waiting you want to check that the Server is free first before running the Serve event? This worked for me when I had an infinite loop in Serve

**Comment by daitenshionyan** [comment]
Hello!!

The problem might actually be in your Serve event where the customer is not removed from the Server's queue after it has been served. If this is the problem, Customer 9 will be served after its Waiting event and then the infinite loop of executing Customer 10's Waiting event as 10 is never first in line. You can check this by printing out the events that are being executed.

Additional stuff...

> I realise that for my waiting queue, I will never get the desired customer I want resulting in infinite loop, and my customer 10 just seems to magically disappear every time.

The print statement for your waiting queue is misleading as what it is printing is not based on the updated server. Instead you might want to print the Server in shop from the very start since this is the Server that you are going to work on instead of the Server in the Event.

An alternative to printing would be to edit the toString() method of Server and Shop such that Server's toString() will include all the variables that you want to see (like its queue) and Shop's toString will include the ImList of Servers. From this, in your SimulateN, just print the Event and Shop after every execution. This way you can see how the Servers are updated every event. An example,
```
while() {
// your hard work
System.out.println(event);
System.out.println(shop);
}
```
where `event` is the Event that you polled out of your PQ and `shop` is the updated Shop.

To simplify your code, you might realise that the state of all Servers are never changed. Assuming the logic of your Waiting is as such (which I think it is):
1. Check if customer is next in line and Server is able to serve.
2. If it is produce a Serve event (the Server's queue will be reduced in the Serve event) if not produce another Waiting event at the next available time of the Server that the customer is queueing on.

Only the Event state is changed (in terms of its time). Thus, the Shop will never be changed too and you can just return the current Shop as the updated Shop for both cases.

**Comment by lyjm21** [comment]
Hi @daitenshionyan ! Thank you so much for the detailed comment, I managed to alter my code such that for DONE and WAIT, it prints the waiting queue of that server. For my serveCust, it does remove the first person in the queue.  
![Screenshot 2022-04-22 at 7 51 08 PM](https://user-images.githubusercontent.com/100070009/164713823-2ccc0db6-6bd5-4c02-ae98-a66762ccbbdb.png)

However, Im still not sure whats wrong w my code. I've adjusted it to not loop for now and it now has the issue of both 9 and 10 getting served at the same time. It appears as if when I have my 7 DONE event at 10.484, it clears the waiting Queue for me. 
<img width="342" alt="Screenshot 2022-04-22 at 8 23 34 PM" src="https://user-images.githubusercontent.com/100070009/164713966-31da438a-3b3f-439c-9f45-970b97e60d35.png">

My DONE event calls this to modify the server, I am not very sure how I can retain 9 in the queue when 7 is done serving. 
![Screenshot 2022-04-22 at 8 27 45 PM](https://user-images.githubusercontent.com/100070009/164714185-5502078f-020f-46f1-bc75-c5238fea3fb1.png)

**Comment by daitenshionyan** [comment]
Again the print statements form Server might be misleading as they are not the updated Servers especially for Done event. This is because between the Server and Done event there is a time gap and customers might have arirved and waited on that same Server. However, the Server stored in the Done event (that it got from the Serve event) will not be updated on this. This causes the Server stored in the Done event and the updated one in Shop to be different.

As for customers 9 and 10 being served at the same time, where are you removing the customer from the Server's queue? Based on your if statements in Waiting event, the logic of Waiting and Serve should be as such:

In Waiting:

1. Check if the customer is next in line and Server is able to serve (this is already in the if statement of your Waiting event)
2. If true, produce a Serve event, otherwise, another Waiting event with its time updated as the (updated) Server's next available time.
3. Return the Event produced in 2 and the SAME shop passed in from the arguments.

In Serve:

1. Retrieve the Server from Shop.
2. Update this Server's next available time and remove the customer from the queue.
3. Update Shop with this Server.
4. Return a Done event and the updated Shop

From this logic, Done event does nothing but return an empty event and the SAME shop in this level.

If this results in an infinite loop, it might then be the way Events are compared. After Customer 9 Waiting is executed, Customer 9's Serve event will be produced. This Serve event should be executed before Customer 10 Waiting, although they are at the same time, to update the Server in Shop that that Server is now serving 9 and cannot serve anyone anymore. The priority of comparison for events can be something like this: Event time > Customer arrival time > Customer ID.

`super.getTime() >= server.getNextAvailableTime()` should be enought to check if the Server is availabe and thus can replace the boolean `isAvailable` (or equivalent) tag inside Server. Make sure that `server` is the updated Server in Shop too.

For debugging, I think it is helpful to make Waiting print out something too so that you know what is going on.
