### ISSUE TITLE
Level 8_2 Server 2 resting at 11.636

### ISSUE THREAD

**Issue by pwintthiri** [nus-cs2030/2122-s2#505]
Hi, my human servers are resting when they're not supposed to. The first time a rest occurs is at 11.636 by Server 2. Server 1 also starts resting after a while.

When doing level 7, I had the rest time as an attribute to Shop and created a new constructor for Shop with the Server list and rest time. In each of the Event classes' return statement, I update the Shop. This includes Events that return Optional.empty() as well. I'm not sure if that's the problem?

I always do this: 
```
Shop newShop = new Shop(updated, shop.getRestTime());
return Pair.<Optional<Event>, Shop>of(Optional.<Event>of(newEvent), newShop);
```

Also to cater to level 8, if the Server is a Self-Checkout, I don't add the rest time to its next available time unlike for a Human Server where I will add it. But I still return the updated Shop with `shop.getRestTime()` for both cases like the above.

**Comment by tungkei** [comment]
Hi, I'm not sure about your level 7 part but for level 8 what I did was check if the server is a self checkout, if it is then I don't call the get for the rest time because it has no rest time, so the next available time will just be the current event time.

**Comment by ChngWC** [comment]
Hi ! 

Same as the comment above ^, what I did was to check if the polled event in my run method if it is being served by a Self-checkout or a human Server. From there, I will be able to get the rest times only when it is a human server.

**Comment by elvern18** [comment]
Hi ! Not sure what shop.getRestTime() do , since shop has a list of servers and they all have different rest time if they want to rest. For me, for level 7, Server has a Supplier<Double> restTime attribute.  In this way, in the Done event, server.getRestTime().get() will be called, which will be added with the eventTime of the Done event to calculate the Server's next available time.  

Then, my SelfCheckout will extends Server, and the Supplier<Double> restTime attribute will then be defaulted to () -> 0.0, so that the restTime will be 0 even if its called. 

Hope this helps!

**Comment by pwintthiri** [comment]
I managed to figure it out, thanks everyone!
