### ISSUE TITLE
Level 4 Practice PA 1 Help

### ISSUE THREAD

**Issue by bryankwe** [nus-cs2030/2122-s2#52]
Hello anyone has hints for this part of level 4?

The test cases from level 4 suggest that Question has abstract methods of answer(), lock() and mark(), but I cant seem to figure out how to get these errors when these methods need to be implemented in child classes of Question

![image](https://user-images.githubusercontent.com/97665622/155672867-c4b01f72-f0d7-4df0-baba-31fe4f7ea77a.png)

**Comment by jingyulim1** [comment]
From it, we see that the object 1.does not have answer method after it is locked, and 2. does not have mark method before it is locked.

This hints after locking, you return a different object that is not Question (since Question has an answer method but the object after locked do not).

Hope this helps.

**Comment by Alexius0123** [comment]
Since the methods are hidden, it is most likely hidden in another class or interface. Based on the question, it would seem that you need an interface for locked objects and another abstract class with a defined method for mark(). Good luck!

**Comment by haoyangw** [comment]
You can also have the lock() function return an Interface type, but within the lock() function body return an Object of a class implementing that interface(so by polymorphism the function compiles and executes fine).

Neat trick about making the return type of the lock() function an Interface type instead of a Class type is a client is forced to store the output of lock() in an Interface variable(not an implementing class, otherwise you get compile type error), which will only have the methods declared in the interface but none of the _other methods_(hint hint, what other methods?) defined in the actual implementing class/object. So this Interface variable will throw cannot find symbol error(hint hint). 

Also, since the Object stored in that Interface variable can be an instance of a class like TFQ, performing e.g. `instanceof TFQ` on that Interface variable will return true, while still giving you the cannot find symbol errors you want.

Think Interface segregation principle, so which methods should go into which interface to give you the cannot find symbol errors you want. Your actual classes(e.g. FillInBlank) can implement all the Interfaces and thus have all the functions(at _runtime_), but depending on the variable type, can still throw _compile time_ errors for 'missing' functions
