### ISSUE TITLE
Level 8_1 Serving 2 customers at the same time

### ISSUE THREAD

**Issue by muhdjabir** [nus-cs2030/2122-s2#538]
# Summary
<img width="300" alt="image" src="https://user-images.githubusercontent.com/99940885/164960033-c0c9b813-0326-462c-8ac8-23f714a7d7a2.png">
<img width="189" alt="image" src="https://user-images.githubusercontent.com/99940885/164960878-62f57500-8b81-47c4-8819-697cbbc7f70a.png">

Hi everyone Im facing an error whereby after a certain point one of my server accidentally serves 2 customers at the same time. My Implementation involves calling a PENDING class after WAIT where in PENDING it checks for what position the customer is in the queue and whether the the server is available. Im thinking the issue either occurs in pending or serving but i cant really pinpoint it?

Attached is my SERVE and PENDING
Serve EXECUTE 
<img width="404" alt="image" src="https://user-images.githubusercontent.com/99940885/164960122-92761320-4976-48da-97c2-20bcf99ed5d3.png">

PENDING EXECUTE
<img width="399" alt="image" src="https://user-images.githubusercontent.com/99940885/164960141-eb84e268-d066-4af9-82e1-d3026f3bf5ae.png">

**Comment by jonyeokj** [comment]
This is probably due to the fact that you're not updating your server queues for your customers properly. I encountered the same problem because the earlier levels didn't account for the queues after a Done Event. My best guess to solve this problem would be to check all your events to make sure that they are properly updating your servers, their busy status, their queues, and subsequently, the Shop state.

Hope this helps and that you manage to solve it soon!

**Comment by Noel-Lee** [comment]
Since your implementation revolves around checking for what position the customer is in the queue and whether the the server is available. Maybe you could check if there is an issue with ur getAvailability. Other than that I am also not sure why you would return a new Serve Event in your else statement in pending execute because it could potentially serve a customer when the server is not available. These are just my suspicions but without fully grasping your implementation it is quite hard to advice accordingly.

**Comment by evelyynnz** [comment]
Hello! i had the same issue too! i think it could possibly be because youre not updating ur shop status/server status correctly. 
I managed to resolve this issue by creating a shop.getCurrentServer(this.server) function in my shop (which identifies the server w same server id as this.server), to get the most recent state of the server. U also have to update the event time of ur pending class correctly. Hope this helps!

**Comment by muhdjabir** [comment]
HI GUYS ive solved the issue! It lied with my rest not updating shop properly thanks all!
