### ISSUE TITLE
project test case 9_10

### ISSUE THREAD

**Issue by evelyynnz** [nus-cs2030/2122-s2#547]
Hi ! anyone knows why I get this output & how i can fix it? I set the qMax of the first self check out server to be qMax * number of self checkout servers & the qmax of the rest of the servers to be 0 so I'm not sure if im getting this error due to my implementation

![Screenshot (221)](https://user-images.githubusercontent.com/98569083/164972365-e0e06ac6-4919-4ed3-85f3-89473ff2724b.png)

**Comment by tristky** [comment]
Hi dear eve, i think i know the answer, this might be because when you implemented your code, it failed to realise that you were using main as a method instead they wanted you to implement it as a User input starts with values representing the number of servers, the number of self-check counters, the maximum queue length, the number of customers and the probability of a server resting. This might also be due to the fact that the implementation you used was wrong and hence there is an error, maybe you can try debugging this so it can work, just so you know i couldnt do this too but im trying my best! hope we can both finish on time

**Comment by jonyeokj** [comment]
Hello, I think the problem lies with how you update your server queues or self-check queues.
I believe the problem is very similar to the one found in this thread, [https://github.com/nus-cs2030/2122-s2/issues/538](538). What I did for most of my debugging is printing the event I'm executing in my Simulate class, or printing the status of the servers during the events. It's worth a shot, especially when debugging for these private test cases.

Hopefully this helps!

**Comment by Alexius0123** [comment]
Hi! Based off the error codes, it would appear that it has something to do with how your self check-out shared queue is implemented. Perhaps you could send your implementation or explain how you update your self check-out shared queue!

**Comment by evelyynnz** [comment]
if im not wrong the qmax in this testcase is 1, thus my qMax for self-checkout 1 would be 2. Based on my understanding, the self-checkout1 could have 2 people waiting but in this case it seems like it can only have 1 person waiting. Is there a flaw in my understanding?

**Comment by tristky** [comment]
Yes, you are absolutely correct with that, as i foresee alot of my counterparts encountering this issue, howeevr the way to work around it is to think outside the box and realise that it is simpler than it really is, however the code you use might be dependent on your level 8 which needs abit of tweaking, but then again please do not trust me as i am encountering the same issue as you with regards to this problem and i dont see myself solving this anytime soon, however i am still trying my best to try my best as this is a tedious test case that i believe everyone should pass before moving on to the second part which is much harder. 

hope we both are able to solve this! jiayous

**Comment by Noel-Lee** [comment]
Not sure about the intended logic for qMax but my qMax for selfcheckout k+1 was the same as the qMax of the rest of the ordinary servers. Passed level 9 so I think that might be that case... I hope..

**Comment by jonyeokj** [comment]
> if im not wrong the qmax in this testcase is 1, thus my qMax for self-checkout 1 would be 2. Based on my understanding, the self-checkout1 could have 2 people waiting but in this case it seems like it can only have 1 person waiting. Is there a flaw in my understanding of this?

No the queues for the Self-Checkouts shouldn't stack on top of on another. They have a SHARED queue, so if the indicated max queue int variable is 2 and there are 2 Self-Checkouts, the queue for the Self-Checkouts should be just 2, not 2*2. I'm quite surprised you managed to pass test case 8_4 with that implementation as there is an instance in that test case whereby many customers leave due to queues being full. You might want to change how your max queue is implemented and instantiated for the Self-Checkout servers, and debug your earlier test cases for level 8.

Also, you can implement the queues like what Noel mentioned earlier, depends on how you implemented your other classes as well.

**Comment by evelyynnz** [comment]
thanks! @tristky hope u solve it soon! follow closely to whatever they said & u shud get there soon! all the best :)
