### ISSUE TITLE
Difference between Overriding and Overloading

### ISSUE THREAD

**Issue by fionaxjy** [nus-cs2030/2122-s2#562]
Hi, I'm still a bit confused about the difference between overriding and overloading a class. Could someone help explain?

**Comment by shotnothing** [comment]
override means child has a different implementation has of a method from a parent. overload means a method can have more than one kind of input

**Comment by Alexius0123** [comment]
> Hi, I'm still a bit confused about the difference between overriding and overloading a class. Could someone help explain?

Hello! So essentially when you override a method, i.e child class overrides a parent's method, when the method is called later on, it will run the child class's implementation of the method rather than the parent's, hence overriding. This can be seen the most obviously from the toString() method that is overrode. If the method is not overrode, it will return the Class name + "@" + memory location. However, after loading we notice that our classes do not return that as the toString() any longer.

On the other hand, overloading involves implementing additional methods into a class that take in different arguments. For example, a class can have both foo() and foo(A a) methods in its class. This means that there are two implementations of foo that returns different things depending on the parameters passed into the methods.

Hope this helps!

**Comment by dorothyyuann** [comment]
Overriding is typically used for child classes that have a method with the same name as the class it extends from/implements

Overloading is for constructor parameters, allowing different methods to be invoked based on the input

E.g. myMethod(int a) and myMethod(String a)

**Comment by evelyynnz** [comment]
Hi! Overriding would mean that a method in the child class replaces the same method in the parent's class & overloading would be having the same method that can take in different parameters. 
An example of overriding would be the toString() method & an example of overloading would be having different constructors for the same class

**Comment by mingshan2705** [comment]
Hi just to add on, overriding would be done across classes (parent, child) whereas overloading would be done within the 
same class

**Comment by shotnothing** [comment]
> Hi just to add on, overriding would be done across classes (parent, child) whereas overloading would be done within the same class

i think you could also overload across classes. it is only overriding that needs to be interclass

**Comment by fionaxjy** [comment]
I've got it now, thanks everyone!

**Comment by shotnothing** [comment]
> Hi just to add on, overriding would be done across classes (parent, child) whereas overloading would be done within the same class

i think you could also overload across classes. it is only overriding that needs to be interclass
