### ISSUE TITLE
Level 6 Timing Update

### ISSUE THREAD

**Issue by dorothyyuann** [nus-cs2030/2122-s2#563]
Between my Buffer class and Serve class there seems to be a different server's PQ<Customer> being invoked such that my Customer 10 is served before Customer 9 finishes being served
![Screenshot24 04_16 22](https://user-images.githubusercontent.com/101258725/164981130-8617e743-010c-44b3-b6c0-cc3dd2c78bab.png)
?

**Comment by fionaxjy** [comment]
Hi sorry, I can't see your photo, could you perhaps upload another one? Thanks!

**Comment by bbelleeee** [comment]
hihi im not sure if its bc the events are not ordered properly and if thats the case maybe u can try to compare customerId in your eventComparator
but like if its because ur wait/pending doesnt check the priority of customers, if u put the servers queue of customers in a priority queue then it will auto sort then just use poll(), but if u put it in like an imlist then u can sort the list first then remove(index 0)
