### ISSUE TITLE
Cannot copy and paste in jshell 

### ISSUE THREAD

**Issue by ongyongen** [nus-cs2030/2122-s2#64]
# Summary
How to copy and paste into jshell 

## Description 
I realised that during the actual lab when I ssh into soc server, I can copy and paste the sentences for the tests from task.txt into jshell using cmd c + cmd v. However, when I attempt the lab at home and cmd c + cmd v, jshell will just freeze and I have to close the window.  Does anyone know why this is so? I tried to google for the issue but nothing came up, so I'm not sure if there is something wrong with my laptop.

**Comment by weiming21** [comment]
Hi I believe it is because the soc server is using jdk 11.0.8 whereas you have installed jdk 11.0.11. You can verify that by running "java -version" in your terminal. Maybe you could try installing and switching to jdk 17 or some other jdks and see if it works for you. Hope this helps!
https://unix.stackexchange.com/questions/654406/cant-paste-into-jshell-version-11-0-11-reproduced-on-two-machines

**Comment by ongyongen** [comment]
It works now! Thanks!
