### ISSUE TITLE
Any tips on how to structure code to avoid Java Reflection / instanceof?

### ISSUE THREAD

**Issue by bryankwe** [nus-cs2030/2122-s2#70]
Hi guys, just wondering if anyone has any tips on how to structure code such that we avoid Java Reflection (.getClass()) or instanceof. 

Of the labs we have been working on, I've encountered this issue a few times where I actually want to check the class / instance of my object.

This is especially so when I have different objects in my ImList (e.g. ImList<Token> containing a list of SafeEntry & Token) and want each type of object will have a different behavior (e.g. different output Strings)

Any help / discussion is greatly appreciated

**Comment by LauWyeRock** [comment]
Replying directly to the example you gave, I think maybe you can create an interface and let both classes implement that interface/abstract class so that you can pull the object out and when you call toString, it will run its own toString?

Otherwise, i think it'd be better if you just separate out diff classes into diff ImLists so you know only those types exist in that ImList

**Comment by szeying02** [comment]
In the case of your example, the `ImList` should have a type `<WriteableDevice>`, which both your `SafeEntry` and `Token` class should extend / implement from. For each type to have a different behaviour in terms of strings, you may want to check if the behaviour is similiar to the `toString()` method previously defined in the respective class. Generally, if there's a slight difference, I would modify the toString() method directly and call on it when returning the values. Hope this helps!
