### ISSUE TITLE
How to remove cyclic dependencies?

### ISSUE THREAD

**Issue by tanweiming00** [nus-cs2030/2122-s2#75]
How did you all remove cyclic dependencies in PA1 Level 3? I initialise Protocol as one of the variables and my constructor initialises it with this.currProtocol = new P1();

Cyclic dependencies detected within:
Case.class -> P1.class
P1.class -> P2.class
P2.class -> P1.class
Grading terminated.

My code works well with jshell but got killed by Codecrunch.

**Comment by jingyulim1** [comment]
Seems like your P1 uses P2 and P2 uses P1 at the same time.

There should be no issue having  `this.currProtocol = new P1(); in Case.

**Comment by tanweiming00** [comment]
Yeap you are right.. I am currently dealing with the hidden test cases..

**Comment by tanweiming00** [comment]
> Seems like your P1 uses P2 and P2 uses P1 at the same time.
> 
> There should be no issue having `this.currProtocol = new P1();` in Case.

How do you exit self-isolation in P2 without violating the cyclic dependencies? I think I will just return new P2();

**Comment by jingyulim1** [comment]
I created another class Discharge (which implements Protocol) which takes in a string that handles all the discharged cases (seek attention, follow up with doctor or complete). 

You can consider using booleans within P2 to manipulate the outcome without creating a new class.

**Comment by alantay11** [comment]
Yeah it's possible to use multiple booleans in both P1 and P2. I think it's theoretically possible to use the list of test results to determine the status but it doesn't seem possible to pass it into the protocols.
 
Maybe you can check if all your isolation logic is kept within each protocol? Or since you're doing lv3, you could leave P2 out until later on so you can find out which file is giving the problem.

**Comment by tanweiming00** [comment]
Anyone has an idea how to deal with this test case? 

![image](https://user-images.githubusercontent.com/97489703/156891860-78f5dd26-f496-4fbc-abaa-5f62685a7699.png)
