### ISSUE TITLE
PA1 

### ISSUE THREAD

**Issue by yongchein-o** [nus-cs2030/2122-s2#86]
![image](https://user-images.githubusercontent.com/88547050/158019365-eeb1076e-2743-42c0-a175-3e2372e6aa9b.png)

Anyone knows how to convert the no constructor error to the error given in the Task?

**Comment by wayneonn** [comment]
Looking at the errors, it seems you may have multiple constructors taking in 2 arguments. You would only need one constructor taking in `Person `and `PCR `only, so you would probably need to remove the rest for it to just throw one error only.

**Comment by yongchein-o** [comment]
but I would need other constructors for my program to work no?
The sample answer has like two constuctors too?
![image](https://user-images.githubusercontent.com/88547050/158020519-faa5740b-0d32-4df8-8d75-6b7a29bf1086.png)

**Comment by wayneonn** [comment]
I see where you are coming from, maybe I wasn't clear enough so my apologies on it. What I mean is that the `Case` constructor should only have 2 arguments taken in, which are `Person` and `PCR`. I think the error being thrown out is due to the compiler seeing there are 2 arguments being passed in, it attempts to find each `Case` constructor which has 2 arguments, thereby showing all the constructors which are able to take in 2 arguments (In this case, line 3,6 and 8 on the right are shown in Codecrunch). 

In the sample solution, it's alright to have the 2 `Case` constructors as they take in 2 arguments and 4 arguments respectively, so one error should only appear for it (Expected error in Codecrunch).

Hope it clarifies for you, thanks.

**Comment by yongchein-o** [comment]
Ah thank you!
